/**
 * Fetches published GitHub releases and regenerates
 * client/src/data/changelog.ts as a static TypeScript file.
 *
 * Seed entries from client/src/data/changelog-seed.ts are merged in for
 * versions that predate GitHub Releases. If a release exists with the same
 * version as a seed entry, the release takes precedence.
 *
 * Usage:
 *   GITHUB_TOKEN=ghp_... npx tsx script/sync-changelog.ts
 *
 * The token only needs `public_repo` (or `repo` for private repos) scope.
 * Without a token the script still works but is subject to lower rate limits.
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const REPO = "bd73-com/fetchthechange";
const OUT = resolve(__dirname, "../client/src/data/changelog.ts");
const SEED = resolve(__dirname, "../client/src/data/changelog-seed.ts");
const PER_PAGE = 100;

interface GitHubRelease {
  tag_name: string;
  published_at: string;
  body: string | null;
  draft: boolean;
  prerelease: boolean;
}

async function fetchAllReleases(): Promise<GitHubRelease[]> {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
  };
  const token = process.env.GITHUB_TOKEN;
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }

  const releases: GitHubRelease[] = [];
  let page = 1;

  while (true) {
    const url = `https://api.github.com/repos/${REPO}/releases?per_page=${PER_PAGE}&page=${page}`;
    const res = await fetch(url, { headers });
    if (!res.ok) {
      throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
    }
    const batch: GitHubRelease[] = await res.json();
    if (batch.length === 0) break;
    releases.push(...batch);
    if (batch.length < PER_PAGE) break;
    page++;
  }

  return releases;
}

function toEntry(r: GitHubRelease) {
  const version = r.tag_name.replace(/^v/, "");
  const date = r.published_at.slice(0, 10); // YYYY-MM-DD
  const body = (r.body ?? "").trim();
  return { version, date, body };
}

interface ChangelogEntry {
  version: string;
  date: string;
  body: string;
}

async function loadSeedEntries(): Promise<ChangelogEntry[]> {
  try {
    const mod = await import(SEED);
    return mod.changelogSeed ?? [];
  } catch {
    console.warn("Could not load seed entries, skipping.");
    return [];
  }
}

async function main() {
  const raw = await fetchAllReleases();
  const releaseEntries = raw
    .filter((r) => !r.draft && !r.prerelease)
    .sort(
      (a, b) =>
        new Date(b.published_at).getTime() -
        new Date(a.published_at).getTime(),
    )
    .map(toEntry);

  // Merge seed entries for versions not covered by GitHub Releases
  const releaseVersions = new Set(releaseEntries.map((e) => e.version));
  const seedEntries = (await loadSeedEntries()).filter(
    (e) => !releaseVersions.has(e.version),
  );
  const entries = [...releaseEntries, ...seedEntries].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime(),
  );

  const lines = [
    "// Auto-generated by script/sync-changelog.ts — do not edit by hand.",
    "",
    "export interface ChangelogEntry {",
    "  version: string;",
    "  date: string;",
    "  body: string;",
    "}",
    "",
    `export const changelog: ChangelogEntry[] = ${JSON.stringify(entries, null, 2)};`,
    "",
  ];

  writeFileSync(OUT, lines.join("\n"), "utf-8");
  console.log(
    `Wrote ${entries.length} entry/ies (${releaseEntries.length} from releases, ${seedEntries.length} from seed) to ${OUT}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
