// Auto-generated by script/sync-changelog.ts — do not edit by hand.

export interface ChangelogEntry {
  version: string;
  date: string;
  body: string;
}

export const changelog: ChangelogEntry[] = [];
